### ISSUE TITLE
Map USGS colours to Modis

### ISSUE THREAD

**Issue by ClaireDons** [Urban-M4/snakemake-wrf#32]
It would be nice to have more uniform colours for the LU_index plots.

**Comment by Peter9192** [comment]
Could use this table for a mapping https://www.researchgate.net/figure/Land-use-mapping-using-the-20-category-IGBP-Modified-MODIS-and-24-category-USGS-schemes_tbl2_262952739

**Comment by ClaireDons** [comment]
That's the one I used but I need to check it over and make sure it is all ok. Also, I think it would be nice to differentiate between all the LCZ categories?
